### ISSUE TITLE
Video Can't Download Because of didn't get video streams 

### ISSUE THREAD

**Issue by ajmalrishad** [yashrathi-git/vimeo_downloader#22]
<img width="960" alt="git" src="https://github.com/yashrathi-git/vimeo-dl/assets/69522541/f68c386c-1f98-4426-9c28-4f547d59eea0">

this is i got when try to download a video using vimeo video url the issue.
this is because of video stream is not get from the vimeo video platform what can i use insted of video stream for download videos 
fetch images and video thumbail are working only issue in download video

**Comment by ghost** [comment]
Can reproduce. When trying to download a video, I get the following error:
```
Traceback (most recent call last):
  File "main.py", line 112, in main
    .streams[0]
     ^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/vimeo_downloader/__init__.py", line 341, in streams
    for stream in js_url["request"]["files"]["progressive"]:
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'progressive'
```

Python version 3.11.9
vimeo-downloader Version: 0.4.1
requests Version: 2.31.0
tqdm Version: 4.66.2
urllib3 Version: 1.25.11

**Comment by ijharulislam** [comment]
Any update on this?

**Comment by ghost** [comment]
You can use yt-dlp as a temporary workaround.
