### ISSUE TITLE
only meta works, streams does not

### ISSUE THREAD

**Issue by xvtstephen** [yashrathi-git/vimeo_downloader#24]
this is on:
```
 uname -a
Linux ASUS 6.8.0-49-generic #49~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Nov  6 17:42:15 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
python --version
Python 3.10.12
```
``` python
>>> v = Vimeo('https://vimeo.com/503166067')
>>> meta = v.metadata
>>> meta.title
"We Don't Have To Know - Keli Holiday"
>>> meta.likes
1061
>>> s = v.streams
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/vimeo_downloader/__init__.py", line 249, in _extractor
    request_conf_link = re.findall(pattern, html.text)[0].replace(
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/stephen/progs/python/vimeo.py", line 15, in <module>
    ## Download video
  File "/usr/local/lib/python3.10/dist-packages/vimeo_downloader/__init__.py", line 335, in streams
    js_url = self._extractor()
  File "/usr/local/lib/python3.10/dist-packages/vimeo_downloader/__init__.py", line 256, in _extractor
    raise UnableToParseHtml("Couldn't find config url")
vimeo_downloader.UnableToParseHtml: Couldn't find config url
```
is there a config file I need?

**Comment by BorjaPintos** [comment]
Same problem, 
I think vimeo changes the way you get the config file...
So... We have to wait for it to be fixed. 
Last commit: 3 years ago...
