### ISSUE TITLE
Private video URLNotSupported

### ISSUE THREAD

**Issue by saper-2** [yashrathi-git/vimeo_downloader#4]
Hi,

I've got video on unsual link, it looks like:
```
https://vimeo.com/123456789/abcdef1234
```
(Number then it's followed by 10 character in hexadecimal - i did not notice other character than 0-9a-f ).

With link above I get error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.7/site-packages/vimeo_downloader/__init__.py", line 179, in __init__
    self._video_id = self._validate_url()  # Video ID at the end of the link
  File "/home/user/.local/lib/python3.7/site-packages/vimeo_downloader/__init__.py", line 202, in _validate_url
    f"{self._url} is not supported. Make sure you don't include query parameters in the url"
vimeo_downloader.URLNotSupported: https://vimeo.com/123456789/abcdef1234 is not supported. Make sure you don't include query parameters in the url
```

Sorry, I can not share the URL 😔

**Comment by yashrathi-git** [comment]
Now you could download video from their vimeo video IDs. Try this:
use the unique numeric part of URL as video ID. 

Get latest version:
```
pip install git+https://github.com/yashrathi-git/vimeo_downloader
```
```py
from vimeo_downloader import Vimeo

cookies = " paste cookie if authentication is required "

v = Vimeo.from_video_id(
    video_id="ID",
    cookies=cookies,
)
best_stream = v.best_stream
title = best_stream.title
download_url = best_stream.direct_url
best_stream.download() # to download video
```

**Comment by saper-2** [comment]
Hi,

So I tried using GitHub version and in video_id the video id and the "code" :

```
saper@spc-deb-vm:~ $ python3
Python 3.7.3 (default, Jan 22 2021, 20:04:44)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from vimeo_downloader import Vimeo
>>> v = Vimeo.from_video_id(video_id="123456789/abcdef1234")
>>> bs = v.best_stream
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/saper/.local/lib/python3.7/site-packages/vimeo_downloader/__init__.py", line 334, in best_stream
    return self.streams[-1]
  File "/home/saper/.local/lib/python3.7/site-packages/vimeo_downloader/__init__.py", line 310, in streams
    js_url = self._extractor()
  File "/home/saper/.local/lib/python3.7/site-packages/vimeo_downloader/__init__.py", line 253, in _extractor
    f"{js_url.status_code}: Unable to retrieve download links"
vimeo_downloader.RequestError: 404: Unable to retrieve download links
```

No luck 😔

**Comment by yashrathi-git** [comment]
@saper-2 
In this example URL `https://vimeo.com/123456789/abcdef1234`, by ID I mean only the numeric part - `123456789` should work if.

**Comment by 89z** [comment]
https://github.com/yashrathi-git/vimeo_downloader/issues/2
