### ISSUE TITLE
why I get this error

### ISSUE THREAD

**Issue by manafn** [yashrathi-git/vimeo_downloader#8]
Traceback (most recent call last):
  File "mk.py", line 21, in <module>
    embedded_on='https://videoboklet.com/show/coursecontent/11')
  File "C:\Users\Manaf\AppData\Local\Programs\Python\Python37\lib\site-packages\vimeo_downloader\__init__.py", line 179, in __init__
    self._video_id = self._validate_url()  # Video ID at the end of the link
  File "C:\Users\Manaf\AppData\Local\Programs\Python\Python37\lib\site-packages\vimeo_downloader\__init__.py", line 197, in _validate_url
    match = re.findall(pattern, self._url)
  File "C:\Users\Manaf\AppData\Local\Programs\Python\Python37\lib\re.py", line 223, in findall
    return _compile(pattern, flags).findall(string)
TypeError: expected string or bytes-like object

**Comment by manafn** [comment]
I faced this error even with your example
